config/routes.rb
Rails.application.routes.draw do

  

  match '', to: 'public/home#show_exposition', constraints: { subdomain: /^(?!www$)(.+)$/i },via: [:get]

  namespace :admin do
  get 'domain/index'
  end

  namespace :admin do
  get 'seller_chains/index'
  end

  namespace :admin do
  get 'seller_chains/new'
  end

  namespace :admin do
    resources :pages,controller: 'pages' do
       member do
        get 'delete'
        get 'toggle_lock'
       end
    end
    
    resources :categories,controller: 'categories' do
       member do
        get 'delete'
       end
    end
    
    
    resources :marketers,controller: 'marketer' do
       member do
        get 'delete'
       end
    end
    
    
     resources :sellers,controller: 'sellers' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'deliver_to_marketer'
       end
    end
    
     resources :comments,controller: 'comments' do
       member do
        get 'delete'
        get 'toggle_lock'
       end
    end
    
         resources :seller_chains,controller: 'seller_chains' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'requests'
       end
    end
    
    
     resources :forms,controller: 'forms' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'show_fields'
        get 'new_field'
        post 'save_fields'
        post 'update_field'
        get 'delete_field'
        get 'edit_field'
        
        get 'new_prop'
        post 'save_props'
        get 'delete_prop'
        get 'edit_prop'
        get 'show_props'
        post 'update_prop'
        
       end
    end
    
    
        resources :products,controller: 'products' do
       member do
        get 'delete'
        get 'block'
        get 'action_block'
        post 'action_block'
        get 'toggle_lock'
       end
    end
    
    
   resources :seller_products,controller: 'seller_products' do
       member do
        get 'delete'
        get 'vijeh'
        get 'toggle_lock'
       end
  end
    

    resources :seller_files,controller: 'seller_files' do
      member do
       get 'delete'
       get 'toggle_lock'
      end
   end

    
    get 'dashboard/setting'
    get 'dashboard/marketer_tasks'
        get 'dashboard/plans'
        get 'dashboard/packs'
        post 'dashboard/pay_plan'
        post 'dashboard/pay_plan_callback'
    post 'dashboard/update_setting'
    
    
  end

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations'}

post '/password/reset/sms' => 'public/home#reset_password', as: :reset_password

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end
  
  namespace :admin do
  get 'dashboard/index'
  get 'dashboard/change_development_mode'
  
  end

  namespace :admin do
  get 'dashboard/login'
  get 'dashboard/sms_service'
  get 'dashboard/setting'
  get 'dashboard/transaction'
  get 'dashboard/profile'
  post 'dashboard/update_profile'
   get 'dashboard/ads'
   get 'dashboard/password'
   post 'dashboard/update_password'
    post 'dashboard/send_ads'
  end

  namespace :admin do
  get 'dashboard/logout'
  end
  get 'update',to: 'public/home#update',:as => :update

  get 'callBackUpgrade',to: 'public/home#callBackUpgrade'
  post 'callBackUpgrade',to: 'public/home#callBackUpgrade'

  get 'product/favorite',to: 'public/home#favorite'
  get 'new_product',to: 'public/home#new_product',:as => :new_product
  get 'new_product/:id',to: 'public/home#new_product'
  post 'create_product/:id',to: 'public/home#create_product',:as => :create_product
  post 'update_product/:id',to: 'public/home#update_product',:as => :update_product

  post 'getFields/:id',to: 'public/home#getFields',:as => :get_fields

  
  get 'upgrade_product/:id/:pos',to: 'public/home#upgrade_product'
  get 'product/:id',to: 'public/home#product',:as => :product_show
  get 'products',to: 'public/home#products',:as => :products_show
  get 'destroy_product',to: 'public/home#destroy_product',:as => :destroy_product
  get 'file/:id',to: 'public/home#file',:as => :file_show
  get 'exposition/show/:id',to: 'public/exposition#show',:as => :exposition_show
  post 'exposition/create_comment',to: 'public/exposition#create_comment',:as => :create_comments
  get 'expositions',to: 'public/exposition#expositions',:as => :expositions_show

  get 'exposition/follow',to: 'public/exposition#follow'
  get 'exposition/rate',to: 'public/exposition#rate'
  get 'page/:permalink' => 'public/home#page',as: :page
  
 namespace :public do
  namespace :home do
    get 'register_exposition'
    post 'save_exposition'
    get 'inbox'
    get 'following'
    get 'following_post'
    get 'category'
    get 'favorites'
    get 'search'
   
    
  end
  
    resources :tickets,controller: 'tickets' do
     member do
        get 'conversation'
        post 'save_conversation'
        
       end
    end
 
  
  
end

  root 'public/home#index'

  namespace :api do
    namespace :v1 do
      
    get 'categories' 
    get 'getEditProduct/:id', action: :getEditProduct
    get 'forgot_password/:phone', action: :forgot_password
    
    get 'subcategories/:id' , action: :subcategories
    get 'expositions/:type',action: :expositions
    get 'exposition/:id',action: :exposition
    get 'tickets/:token',action: :tickets
    get 'conversation/:token',action: :conversation
    get 'profile/:token',action: :profile
    get 'update_password/:token',action: :update_password
    get 'update_profile/:token',action: :update_profile
    post 'updateProduct/:id',action: :updateProduct
    get 'product_categories/:token',action: :product_categories
    get 'slider',action: :slider
    get 'category_fields/:token',action: :category_fields
    get 'save_product/:token',action: :save_product
    get 'verify/:token',action: :verify
    get 'check_username/:identity',action: :check_username
    
    get 'register_exposition',action: :register_exposition
    
    post 'save_product/:token',action: :save_product
    post 'register_exposition_c',action: :register_exposition_c
    
    
    get 'delete_product/:token',action: :delete_product
    get 'search/:type',action: :search
    get 'exposition_comments/:id',action: :exposition_comments
    
    
    get 'favorite/:token',action: :favorite
    get 'marketer_sellers/:token',action: :marketer_sellers
    get 'add_seller/:token',action: :add_seller
    
    get 'follow/:id',action: :follow
    get 'following/:token',action: :following
    get 'exposition_filters/:id',action: :exposition_filters
    get 'filter/:id',action: :filter
    get 'build_conversation/:token',action: :build_conversation
    get 'checkNewMessage/:token',action: :checkNewMessage
    get 'startmessage/:token',action: :startmessage
    get 'hasNewTickets/:token',action: :hasNewTickets
    
    
    post 'save_product_image/:id',action: :save_product_image
    get 'nearby',action: :nearby
    get 'show_exposition/:id',action: :show_exposition
    get 'products/:type',action: :products
    get 'product/:id',action: :product
    get 'save_comment/:id',action: :save_comment
    
    get 'favorites/:token',action: :favorites
    get 'product_comments/:id',action: :product_comments
    match 'login',via: [:get,:post,:options]
    match 'register',via: [:get,:post,:options]
      

    end
    
    
  end
  
  
  
  
end

app/views/admin/pages/destroy.html.erb
<h1>Admin::Page#destroy</h1>
<p>Find me in app/views/admin/page/destroy.html.erb</p>

app/views/admin/pages/edit.html.erb
<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">
        
        
        
        
        
 <div class="row">
    <% if @page.errors.full_messages.any? %>
      <% @page.errors.full_messages.each do |error_message| %>
        <% content_for :head do %>
          <%= toast(error_message,4000,['red']) %>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for @page ,url: admin_page_path(@page),html: {class: 'col s12'}, method: :patch do |f| %>
      <div class="row">

        <div class="input-field col s12">
          <%= f.text_field :title,class: 'validate', required: "required" %>
          <%= f.label :title, 'عنوان صفحه' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        <div class="input-field col s12">
          <%= f.text_field :permalink,class: 'validate', required: "required" %>
          <%= f.label :title, 'پرمالینک' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
    
        
        <div class="input-field col s12">
          <%= f.text_field :permalink,class: 'validate', required: "required" %>
          <%= f.label :title, 'تگ ها' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>  
        
        
        <div class=" col s12">
          <%= f.check_box :comment,class: 'filled-in' %>
          <%= f.label :comment, 'نظرات' %>
        </div>
        
     
     
      
      <div class="row">
        <div class="input-field col s12">
          
          <%= f.text_area :content ,class: "materialize-textarea" %>
          <%= f.label :content, 'محتوا' %>
        </div>
        
      </div>
      
         <div class=" col s12">
          <%= f.check_box :layout,class: 'filled-in' %>
          <%= f.label :layout, 'لایه' ,checked: 'checked',class: 'right' %>
        </div>
      
      
     </div>
       
      <div class="row">
        <%= button_tag :type => 'submit', :class => "waves-effect waves-light btn" do %>
         <%= t('crud.create') %> <i class="material-icons right">cloud</i>
        <% end %>
        <%= link_to(raw('<i class="material-icons right">delete_forever</i>'+ t('crud.delete') ),delete_admin_page_path(@page.id),class: 'btn waves-effect waves-light red') %>
      </div>
      
      
      
      
    <% end %>
  </div>
        
        
        
            
            
          
          
        </div>
      </div>
 </div>

</main>

app/views/admin/pages/index.html.erb
<%# content_for :head do %>
  
  
<%# end %>

<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">

        <table class='striped highlight bordered'>
            <thead>
              <tr>
                  <th>ویرایش</th>
                 
                  <th>پرمالینک</th>
  <th>نام صفحه</th>
              </tr>
            </thead>
    
            <tbody>
            <% @pages.each do |page| %>
              <tr>
                <td>
                  <%= link_to(raw('<i class="material-icons">delete_forever</i>'),delete_admin_page_path(page.id),class: 'small btn-floating waves-effect btn-small waves-light red', :data => {:confirm => t('alert.are_you_sure_delete')}) %>
                  <%= link_to(raw('<i class="material-icons">mode_edit</i>'),edit_admin_page_path(page.id),class: 'small btn-floating waves-effect btn-small waves-light blue') %>
                  <%= link_to(raw("<i class='material-icons'>#{page.lock? ? 'lock_outline':'lock_open'}</i>"),toggle_lock_admin_page_path(page.id),class: 'small btn-floating waves-effect btn-small waves-light green') %>
                  <%= link_to(raw("<i class='material-icons'>cast</i>"),admin_page_path(page.id),class: 'small btn-floating waves-effect btn-small waves-light purple') %>
                </td>
                <td><%= page.permalink %></td>
                <td><%= page.title %></td>
              </tr>
            <% end %>
              
              
            
            </tbody>
          </table>
            
            
          
          
        </div>
      </div>
 </div>
<%= link_to(raw('<i class="material-icons">add</i>'),new_admin_page_path,class: 'btn-floating btn-large waves-effect waves-light red',style: 'position:fixed;bottom: 20px; left: 24px;') %>
</main>

app/views/admin/pages/new.html.erb
<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">
        
        
        
        
        
 <div class="row">
    <% if @page.errors.full_messages.any? %>
      <% @page.errors.full_messages.each do |error_message| %>
        <% content_for :head do %>
          <%= toast(error_message,4000,['red']) %>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for @page ,url: admin_pages_path,html: {class: 'col s12'},method: :POST do |f| %>
      <div class="row">

        <div class="input-field col s12">
          <%= f.text_field :title,class: 'validate', required: "required" %>
          <%= f.label :title, 'عنوان صفحه' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        <div class="input-field col s12">
          <%= f.text_field :permalink,class: 'validate', required: "required" %>
          <%= f.label :title, 'پرمالینک' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
    
        
        <div class="input-field col s12">
          <%= f.text_field :permalink,class: 'validate', required: "required" %>
          <%= f.label :title, 'تگ ها' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>  
        
        
        <div class=" col s12">
          <%= f.check_box :comment,class: 'filled-in' %>
          <%= f.label :comment, 'نظرات' %>
        </div>
        
     
     
      
      <div class="row">
        <div class="input-field col s12">
          
          <%= f.text_area :content ,class: "materialize-textarea" %>
          <%= f.label :content, 'محتوا' %>
        </div>
        
      </div>
      
         <div class=" col s12">
          <%= f.check_box :layout,class: 'filled-in' %>
          <%= f.label :layout, 'لایه' ,checked: 'checked',class: 'right' %>
        </div>
      
      
     </div>
       
      <div class="row">
      
        <%= button_tag :type => 'submit', :class => "waves-effect waves-light btn" do %>
         <i class="material-icons left">cloud</i>ثبت
        <% end %>
    

      </div>
      
      
      
      
    <% end %>
  </div>
        
        
        
            
            
          
          
        </div>
      </div>
 </div>

</main>

app/views/admin/pages/show.html.erb
<h1>Admin::Page#show</h1>
<p>Find me in app/views/admin/page/show.html.erb</p>