config/routes.rb
Rails.application.routes.draw do

  

  match '', to: 'public/home#show_exposition', constraints: { subdomain: /^(?!www$)(.+)$/i },via: [:get]

  namespace :admin do
  get 'domain/index'
  end

  namespace :admin do
  get 'seller_chains/index'
  end

  namespace :admin do
  get 'seller_chains/new'
  end

  namespace :admin do
    resources :pages,controller: 'pages' do
       member do
        get 'delete'
        get 'toggle_lock'
       end
    end
    
    resources :categories,controller: 'categories' do
       member do
        get 'delete'
       end
    end
    
    
    resources :marketers,controller: 'marketer' do
       member do
        get 'delete'
       end
    end
    
    
     resources :sellers,controller: 'sellers' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'deliver_to_marketer'
       end
    end
    
     resources :comments,controller: 'comments' do
       member do
        get 'delete'
        get 'toggle_lock'
       end
    end
    
         resources :seller_chains,controller: 'seller_chains' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'requests'
       end
    end
    
    
     resources :forms,controller: 'forms' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'show_fields'
        get 'new_field'
        post 'save_fields'
        post 'update_field'
        get 'delete_field'
        get 'edit_field'
        
        get 'new_prop'
        post 'save_props'
        get 'delete_prop'
        get 'edit_prop'
        get 'show_props'
        post 'update_prop'
        
       end
    end
    
    
        resources :products,controller: 'products' do
       member do
        get 'delete'
        get 'block'
        get 'action_block'
        post 'action_block'
        get 'toggle_lock'
       end
    end
    
    
   resources :seller_products,controller: 'seller_products' do
       member do
        get 'delete'
        get 'vijeh'
        get 'toggle_lock'
       end
  end
    

    resources :seller_files,controller: 'seller_files' do
      member do
       get 'delete'
       get 'toggle_lock'
      end
   end

    
    get 'dashboard/setting'
    get 'dashboard/marketer_tasks'
        get 'dashboard/plans'
        get 'dashboard/packs'
        post 'dashboard/pay_plan'
        post 'dashboard/pay_plan_callback'
    post 'dashboard/update_setting'
    
    
  end

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations'}

post '/password/reset/sms' => 'public/home#reset_password', as: :reset_password

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end
  
  namespace :admin do
  get 'dashboard/index'
  get 'dashboard/change_development_mode'
  
  end

  namespace :admin do
  get 'dashboard/login'
  get 'dashboard/sms_service'
  get 'dashboard/setting'
  get 'dashboard/transaction'
  get 'dashboard/profile'
  post 'dashboard/update_profile'
   get 'dashboard/ads'
   get 'dashboard/password'
   post 'dashboard/update_password'
    post 'dashboard/send_ads'
  end

  namespace :admin do
  get 'dashboard/logout'
  end
  get 'update',to: 'public/home#update',:as => :update

  get 'callBackUpgrade',to: 'public/home#callBackUpgrade'
  post 'callBackUpgrade',to: 'public/home#callBackUpgrade'

  get 'product/favorite',to: 'public/home#favorite'
  get 'new_product',to: 'public/home#new_product',:as => :new_product
  get 'new_product/:id',to: 'public/home#new_product'
  post 'create_product/:id',to: 'public/home#create_product',:as => :create_product
  post 'update_product/:id',to: 'public/home#update_product',:as => :update_product

  post 'getFields/:id',to: 'public/home#getFields',:as => :get_fields

  
  get 'upgrade_product/:id/:pos',to: 'public/home#upgrade_product'
  get 'product/:id',to: 'public/home#product',:as => :product_show
  get 'products',to: 'public/home#products',:as => :products_show
  get 'destroy_product',to: 'public/home#destroy_product',:as => :destroy_product
  get 'file/:id',to: 'public/home#file',:as => :file_show
  get 'exposition/show/:id',to: 'public/exposition#show',:as => :exposition_show
  post 'exposition/create_comment',to: 'public/exposition#create_comment',:as => :create_comments
  get 'expositions',to: 'public/exposition#expositions',:as => :expositions_show

  get 'exposition/follow',to: 'public/exposition#follow'
  get 'exposition/rate',to: 'public/exposition#rate'
  get 'page/:permalink' => 'public/home#page',as: :page
  
 namespace :public do
  namespace :home do
    get 'register_exposition'
    post 'save_exposition'
    get 'inbox'
    get 'following'
    get 'following_post'
    get 'category'
    get 'favorites'
    get 'search'
   
    
  end
  
    resources :tickets,controller: 'tickets' do
     member do
        get 'conversation'
        post 'save_conversation'
        
       end
    end
 
  
  
end

  root 'public/home#index'

  namespace :api do
    namespace :v1 do
      
    get 'categories' 
    get 'getEditProduct/:id', action: :getEditProduct
    get 'forgot_password/:phone', action: :forgot_password
    
    get 'subcategories/:id' , action: :subcategories
    get 'expositions/:type',action: :expositions
    get 'exposition/:id',action: :exposition
    get 'tickets/:token',action: :tickets
    get 'conversation/:token',action: :conversation
    get 'profile/:token',action: :profile
    get 'update_password/:token',action: :update_password
    get 'update_profile/:token',action: :update_profile
    post 'updateProduct/:id',action: :updateProduct
    get 'product_categories/:token',action: :product_categories
    get 'slider',action: :slider
    get 'category_fields/:token',action: :category_fields
    get 'save_product/:token',action: :save_product
    get 'verify/:token',action: :verify
    get 'check_username/:identity',action: :check_username
    
    get 'register_exposition',action: :register_exposition
    
    post 'save_product/:token',action: :save_product
    post 'register_exposition_c',action: :register_exposition_c
    
    
    get 'delete_product/:token',action: :delete_product
    get 'search/:type',action: :search
    get 'exposition_comments/:id',action: :exposition_comments
    
    
    get 'favorite/:token',action: :favorite
    get 'marketer_sellers/:token',action: :marketer_sellers
    get 'add_seller/:token',action: :add_seller
    
    get 'follow/:id',action: :follow
    get 'following/:token',action: :following
    get 'exposition_filters/:id',action: :exposition_filters
    get 'filter/:id',action: :filter
    get 'build_conversation/:token',action: :build_conversation
    get 'checkNewMessage/:token',action: :checkNewMessage
    get 'startmessage/:token',action: :startmessage
    get 'hasNewTickets/:token',action: :hasNewTickets
    
    
    post 'save_product_image/:id',action: :save_product_image
    get 'nearby',action: :nearby
    get 'show_exposition/:id',action: :show_exposition
    get 'products/:type',action: :products
    get 'product/:id',action: :product
    get 'save_comment/:id',action: :save_comment
    
    get 'favorites/:token',action: :favorites
    get 'product_comments/:id',action: :product_comments
    match 'login',via: [:get,:post,:options]
    match 'register',via: [:get,:post,:options]
      

    end
    
    
  end
  
  
  
  
end

app/controllers/admin/marketer_controller.rb
class Admin::MarketerController < ApplicationController
  layout 'admin'
  before_action :admin_auth
  before_action :find_marketer, except: [:index,:new]
  
  def index
    @users=User.marketers
  end

  def new
    @user=User.new
  end

  def edit
  end

  def show
    @users=@user.marketer_subscribers
  end
  def create 
    @user = User.new(marketers_white_list)
    @user.level = 2
    if @user.save
      flash[:notice]=[5000,t('admin.toast.marketer_create')]
      redirect_to admin_marketers_path
    else
      render('new') 
    end  
    
  end
  def destroy
    
    
  end
  
  def delete
    if @user.destroy
      flash[:notice]=[5000,t("admin.toast.RemoveMarketer")]
      redirect_to admin_marketers_path 
    else
      flash[:notice]=[5000,t("admin.toast.cantRemoveMarketer")]
      redirect_to admin_marketers_index_path
    end
  end
  
  
  def update
   if @marketer.update_attributes(marketers_white_list) && @marketer.valid?
      flash[:notice]=[5000,t('admin.toast.marketer_updated')]
      redirect_to admin_marketers_path
   else
     render('edit')
   end
  end
  
  private
  
  def find_marketer
    @user=User.find(params[:id]) rescue ''
  end
  
  def marketers_white_list
   params.require(:user).permit(:email,:name,:phone,:national_code,:password,:password_confirmation) 
  end
  
end

app/helpers/admin/marketer_helper.rb
module Admin::MarketerHelper
end

app/views/admin/marketer/edit.html.erb
<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">
        
        
        
        
        
 <div class="row">
    <% if @user.errors.full_messages.any? %>
      <% @user.errors.full_messages.each do |error_message| %>
        <% content_for :head do %>
          <%= toast(error_message,4000,['red']) %>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for @user ,url: admin_marketers_path,html: {class: 'col s12'},method: :POST do |f| %>
      <div class="row">

        <div class="input-field col s12">
          <%= f.text_field :name,class: 'validate', required: "required" %>
          <%= f.label :name, 'نام و نام خانوادگی' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
         <div class="input-field col s12">
          <%= f.text_field :email,class: 'validate', required: "required" %>
          <%= f.label :email, 'ایمیل' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        <div class="input-field col s12">
          <%= f.text_field :phone,class: 'validate', required: "required" %>
          <%= f.label :phone, 'موبایل' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
    
        
        <div class="input-field col s12">
          <%= f.text_field :national_code,class: 'validate', required: "required" %>
          <%= f.label :national_code, 'کد ملی' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>  
        
       
      <div class="row">
      
        <%= button_tag :type => 'submit', :class => "waves-effect waves-light btn" do %>
         <i class="material-icons left">cloud</i>ثبت
        <% end %>
    

      </div>
      
      
      
      
    <% end %>
  </div>
        
        
        
            
            
          
          
        </div>
      </div>
 </div>

</main>

app/views/admin/marketer/index.html.erb
<%# content_for :head do %>
  
  
<%# end %>

<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">

        <table class='striped highlight bordered'>
            <thead>
              <tr>
                  <th>ویرایش</th>
                 
                  <th>تلفن</th>
  <th>نام </th>
              </tr>
            </thead>
    
            <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to(raw('<i class="material-icons">delete_forever</i>'),delete_admin_marketer_path(user.id),class: 'small btn-floating waves-effect btn-small waves-light red', :data => {:confirm => t('alert.are_you_sure_delete')}) %>
                  <%= link_to(raw('<i class="material-icons">mode_edit</i>'),edit_admin_marketer_path(user.id),class: 'small btn-floating waves-effect btn-small waves-light blue') %>
                  <%= link_to(raw("<i class='material-icons'>#{user.id? ? 'lock_outline':'lock_open'}</i>"),toggle_lock_admin_page_path(user.id),class: 'small btn-floating waves-effect btn-small waves-light green') %>
                  <%= link_to(raw("<i class='material-icons'>cast</i>"),admin_marketer_path(user.id),class: 'small btn-floating waves-effect btn-small waves-light purple') %>
                </td>
                <td><%= user.phone %></td>
                <td><%= user.name %></td>
              </tr>
            <% end %>
              
              
            
            </tbody>
          </table>
            
            
          
          
        </div>
      </div>
 </div>
<%= link_to(raw('<i class="material-icons">add</i>'),new_admin_marketer_path,class: 'btn-floating btn-large waves-effect waves-light red',style: 'position:fixed;bottom: 20px; left: 24px;') %>
</main>

app/views/admin/marketer/new.html.erb
<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">
        
        
        
        
        
 <div class="row">
    <% if @user.errors.full_messages.any? %>
      <% @user.errors.full_messages.each do |error_message| %>
        <% content_for :head do %>
          <%= toast(error_message,4000,['red']) %>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for @user ,url: admin_marketers_path,html: {class: 'col s12'},method: :POST do |f| %>
      <div class="row">

        <div class="input-field col s12">
          <%= f.text_field :name,class: 'validate', required: "required" %>
          <%= f.label :name, 'نام و نام خانوادگی' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
         <div class="input-field col s12">
          <%= f.text_field :email,class: 'validate', required: "required" %>
          <%= f.label :email, 'ایمیل' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
          <div class="input-field col s12">
    <%= f.label :password,value: 'رمز عبور' %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", required: "required" %>
  </div>

  <div class="input-field col s12">
    <%= f.label :password_confirmation,value: 'تایید رمز عبور' %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", required: "required" %>
  </div>
  
        <div class="input-field col s12">
          <%= f.text_field :phone,class: 'validate', required: "required" %>
          <%= f.label :phone, 'موبایل' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
    
        
        <div class="input-field col s12">
          <%= f.text_field :national_code,class: 'validate', required: "required" %>
          <%= f.label :national_code, 'کد ملی' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>  
        
       
      <div class="row">
      
        <%= button_tag :type => 'submit', :class => "waves-effect waves-light btn" do %>
         <i class="material-icons left">cloud</i>ثبت
        <% end %>
    

      </div>
      
      
      
      
    <% end %>
  </div>
        
        
        
            
            
          
          
        </div>
      </div>
 </div>

</main>

app/views/admin/marketer/show.html.erb
<%# content_for :head do %>
  
  
<%# end %>

<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">

        <table class='striped highlight bordered'>
            <thead>
              <tr>
                  <th>ویرایش</th>
                 <th>بازاریاب</th>
                  <th>تلفن</th>
  <th>نام </th>
              </tr>
            </thead>
    
            <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to(raw('<i class="material-icons">delete_forever</i>'),delete_admin_seller_path(user.id),class: 'small btn-floating waves-effect btn-small waves-light red', :data => {:confirm => t('alert.are_you_sure_delete')}) %>
                  <%= link_to(raw('<i class="material-icons">mode_edit</i>'),edit_admin_seller_path(user.id),class: 'small btn-floating waves-effect btn-small waves-light blue') %>
                  <%= link_to(raw("<i class='material-icons'>#{user.exposition_accept? ? 'lock_open':'lock_outline'}</i>"),toggle_lock_admin_seller_path(user.id),class: "small btn-floating waves-effect btn-small waves-light  #{user.exposition_accept? ? 'green':'yellow' }") %>
                  <%= link_to(raw("<i class='material-icons'>cast</i>"),admin_seller_path(user.id),class: 'small btn-floating waves-effect btn-small waves-light purple') %>
                </td>
                <td><%= user.marketer.nil? ? 'ندارد':user.marketer.name %></td>
                <td><%= user.phone %></td>
                <td><%= user.name %></td>
              </tr>
            <% end %>
              
            </tbody>
          </table>
          
        </div>
      </div>
 </div>
<%= link_to(raw('<i class="material-icons">add</i>'),new_admin_seller_path,class: 'btn-floating btn-large waves-effect waves-light red',style: 'position:fixed;bottom: 20px; left: 24px;') %>
</main>