config/routes.rb
Rails.application.routes.draw do

  

  match '', to: 'public/home#show_exposition', constraints: { subdomain: /^(?!www$)(.+)$/i },via: [:get]

  namespace :admin do
  get 'domain/index'
  end

  namespace :admin do
  get 'seller_chains/index'
  end

  namespace :admin do
  get 'seller_chains/new'
  end

  namespace :admin do
    resources :pages,controller: 'pages' do
       member do
        get 'delete'
        get 'toggle_lock'
       end
    end
    
    resources :categories,controller: 'categories' do
       member do
        get 'delete'
       end
    end
    
    
    resources :marketers,controller: 'marketer' do
       member do
        get 'delete'
       end
    end
    
    
     resources :sellers,controller: 'sellers' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'deliver_to_marketer'
       end
    end
    
     resources :comments,controller: 'comments' do
       member do
        get 'delete'
        get 'toggle_lock'
       end
    end
    
         resources :seller_chains,controller: 'seller_chains' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'requests'
       end
    end
    
    
     resources :forms,controller: 'forms' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'show_fields'
        get 'new_field'
        post 'save_fields'
        post 'update_field'
        get 'delete_field'
        get 'edit_field'
        
        get 'new_prop'
        post 'save_props'
        get 'delete_prop'
        get 'edit_prop'
        get 'show_props'
        post 'update_prop'
        
       end
    end
    
    
        resources :products,controller: 'products' do
       member do
        get 'delete'
        get 'block'
        get 'action_block'
        post 'action_block'
        get 'toggle_lock'
       end
    end
    
    
   resources :seller_products,controller: 'seller_products' do
       member do
        get 'delete'
        get 'vijeh'
        get 'toggle_lock'
       end
  end
    

    resources :seller_files,controller: 'seller_files' do
      member do
       get 'delete'
       get 'toggle_lock'
      end
   end

    
    get 'dashboard/setting'
    get 'dashboard/marketer_tasks'
        get 'dashboard/plans'
        get 'dashboard/packs'
        post 'dashboard/pay_plan'
        post 'dashboard/pay_plan_callback'
    post 'dashboard/update_setting'
    
    
  end

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations'}

post '/password/reset/sms' => 'public/home#reset_password', as: :reset_password

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end
  
  namespace :admin do
  get 'dashboard/index'
  get 'dashboard/change_development_mode'
  
  end

  namespace :admin do
  get 'dashboard/login'
  get 'dashboard/sms_service'
  get 'dashboard/setting'
  get 'dashboard/transaction'
  get 'dashboard/profile'
  post 'dashboard/update_profile'
   get 'dashboard/ads'
   get 'dashboard/password'
   post 'dashboard/update_password'
    post 'dashboard/send_ads'
  end

  namespace :admin do
  get 'dashboard/logout'
  end
  get 'update',to: 'public/home#update',:as => :update

  get 'callBackUpgrade',to: 'public/home#callBackUpgrade'
  post 'callBackUpgrade',to: 'public/home#callBackUpgrade'

  get 'product/favorite',to: 'public/home#favorite'
  get 'new_product',to: 'public/home#new_product',:as => :new_product
  get 'new_product/:id',to: 'public/home#new_product'
  post 'create_product/:id',to: 'public/home#create_product',:as => :create_product
  post 'update_product/:id',to: 'public/home#update_product',:as => :update_product

  post 'getFields/:id',to: 'public/home#getFields',:as => :get_fields

  
  get 'upgrade_product/:id/:pos',to: 'public/home#upgrade_product'
  get 'product/:id',to: 'public/home#product',:as => :product_show
  get 'products',to: 'public/home#products',:as => :products_show
  get 'destroy_product',to: 'public/home#destroy_product',:as => :destroy_product
  get 'file/:id',to: 'public/home#file',:as => :file_show
  get 'exposition/show/:id',to: 'public/exposition#show',:as => :exposition_show
  post 'exposition/create_comment',to: 'public/exposition#create_comment',:as => :create_comments
  get 'expositions',to: 'public/exposition#expositions',:as => :expositions_show

  get 'exposition/follow',to: 'public/exposition#follow'
  get 'exposition/rate',to: 'public/exposition#rate'
  get 'page/:permalink' => 'public/home#page',as: :page
  
 namespace :public do
  namespace :home do
    get 'register_exposition'
    post 'save_exposition'
    get 'inbox'
    get 'following'
    get 'following_post'
    get 'category'
    get 'favorites'
    get 'search'
   
    
  end
  
    resources :tickets,controller: 'tickets' do
     member do
        get 'conversation'
        post 'save_conversation'
        
       end
    end
 
  
  
end

  root 'public/home#index'

  namespace :api do
    namespace :v1 do
      
    get 'categories' 
    get 'getEditProduct/:id', action: :getEditProduct
    get 'forgot_password/:phone', action: :forgot_password
    
    get 'subcategories/:id' , action: :subcategories
    get 'expositions/:type',action: :expositions
    get 'exposition/:id',action: :exposition
    get 'tickets/:token',action: :tickets
    get 'conversation/:token',action: :conversation
    get 'profile/:token',action: :profile
    get 'update_password/:token',action: :update_password
    get 'update_profile/:token',action: :update_profile
    post 'updateProduct/:id',action: :updateProduct
    get 'product_categories/:token',action: :product_categories
    get 'slider',action: :slider
    get 'category_fields/:token',action: :category_fields
    get 'save_product/:token',action: :save_product
    get 'verify/:token',action: :verify
    get 'check_username/:identity',action: :check_username
    
    get 'register_exposition',action: :register_exposition
    
    post 'save_product/:token',action: :save_product
    post 'register_exposition_c',action: :register_exposition_c
    
    
    get 'delete_product/:token',action: :delete_product
    get 'search/:type',action: :search
    get 'exposition_comments/:id',action: :exposition_comments
    
    
    get 'favorite/:token',action: :favorite
    get 'marketer_sellers/:token',action: :marketer_sellers
    get 'add_seller/:token',action: :add_seller
    
    get 'follow/:id',action: :follow
    get 'following/:token',action: :following
    get 'exposition_filters/:id',action: :exposition_filters
    get 'filter/:id',action: :filter
    get 'build_conversation/:token',action: :build_conversation
    get 'checkNewMessage/:token',action: :checkNewMessage
    get 'startmessage/:token',action: :startmessage
    get 'hasNewTickets/:token',action: :hasNewTickets
    
    
    post 'save_product_image/:id',action: :save_product_image
    get 'nearby',action: :nearby
    get 'show_exposition/:id',action: :show_exposition
    get 'products/:type',action: :products
    get 'product/:id',action: :product
    get 'save_comment/:id',action: :save_comment
    
    get 'favorites/:token',action: :favorites
    get 'product_comments/:id',action: :product_comments
    match 'login',via: [:get,:post,:options]
    match 'register',via: [:get,:post,:options]
      

    end
    
    
  end
  
  
  
  
end

app/controllers/admin/forms_controller.rb
class Admin::FormsController < ApplicationController
 layout 'admin'
 before_action :find_form,:only => [:show,:update,:edit,:delete,:toggle_lock,:show_fields,:new_field,:save_fields]
 
  def index
    @forms=ProductType.all
  end
  
  def new
    @form=ProductType.new
  end
  
  def toggle_lock
    @form.update_attribute(:lock,!@form.lock)
    flash[:notice]=[5000,t("admin.toast.form_lock_#{@form.lock}")]
    redirect_to admin_forms_path
  end
  
  def create
      @form=ProductType.new(forms_white_list)
    if @form.save
      flash[:notice]=[5000,t('admin.toast.form_create')]
      redirect_to admin_forms_path
    else
      render('new') 
    end
  end

  def show
    
  end
  
 
  
  

  def edit
  end
  
  def delete
    if @form.destroy
      flash[:notice]=[5000,t('admin.toast.form_destroy')]
      redirect_to admin_forms_path
    else
      render('new') 
    end
  end
  
  def update
    if @form.update_attributes(forms_white_list)
      flash[:notice]=[5000,t('admin.toast.form_update')]
      redirect_to admin_forms_path
    else
      render('new') 
    end
  end
  
  # Fields manager 
  
  def show_fields
    @fields=@form.fields
    
  end
  
  def new_field
    @field=@form.fields.new
  end
  
  def save_fields
    @field=@form.fields.new(fields_white_list)
    @field.categories=[params[:product_field][:categories]]

    if @field.save
      
           flash[:notice]=[5000,t('admin.toast.field_create')]
      redirect_to show_fields_admin_form_path(@field.product_type_id)
    else
          render 'new_field' 
    end
  end
  
  def edit_field
     @field=ProductField.find(params[:id])
  end

  def update_field
    @field=ProductField.find(params[:id])
    @field.update_attributes(fields_white_list)
    @field.categories=[params[:product_field][:categories]]
    @field.save
    flash[:notice]=[5000,t('admin.toast.field_update')]
    redirect_to :back
  end
  
  def delete_field
    @field=ProductField.find(params[:id])
    @field.destroy
    flash[:notice]=[5000,t('admin.toast.field_delete')]
    redirect_to show_fields_admin_form_path(@field.product_type_id)
  end
  
  
  
  # Props manager 
  
  def show_props
    @props=ProductField.find(params[:id]).props
    
  end
  
  def new_prop
    @prop=ProductField.find(params[:id]).props.new
  end
  
  def save_props
    @props=ProductField.find(params[:id]).props.new(props_white_list)
    
    if @props.save
      
           flash[:notice]=[5000,t('admin.toast.prop_create')]
      redirect_to show_props_admin_form_path(@props.product_field_id)
    else
          render 'new_prop' 
    end
  end
  
  def edit_prop
     @prop=Prop.find(params[:id])
  end
  

  def update_prop
    @props=Prop.find(params[:id])
    @props.update_attributes(props_white_list)
    flash[:notice]=[5000,t('admin.toast.prop_update')]
    redirect_to show_props_admin_form_path(@props.product_field_id)
 end


  def delete_prop
    @prop=Prop.find(params[:id])
    @prop.destroy
    flash[:notice]=[5000,t('admin.toast.prop_delete')]
    redirect_to show_props_admin_form_path(@prop.product_field_id)
  end
  
  
  private
  def find_form
    @form=ProductType.find(params[:id])
  end
  
  def forms_white_list
    params.require(:product_type).permit(:name,:permalink)
  end
  
  def fields_white_list
    params.require(:product_field).permit(:name,:permalink,:field_type,:categories)
  end
  
  def props_white_list
    params.require(:prop).permit(:name,:permalink)
  end
  
end

app/helpers/admin/forms_helper.rb
module Admin::FormsHelper
end

app/views/admin/forms/edit.html.erb
<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">
        
        
        
        
        
 <div class="row">
    <% if @form.errors.full_messages.any? %>
      <% @form.errors.full_messages.each do |error_message| %>
        <% content_for :head do %>
          <%= toast(error_message,4000,['red']) %>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for @form ,url: admin_form_path(@form),html: {class: 'col s12'}, method: :patch do |f| %>
      <div class="row">

        <div class="input-field col s12">
          <%= f.text_field :name,class: 'validate', required: "required" %>
          <%= f.label :name, 'نام فرم' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        <div class="input-field col s12">
          <%= f.text_field :permalink,class: 'validate', required: "required" %>
          <%= f.label :permalink, 'پرمالینک' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
    
        

    
      
      
     </div>
       
      <div class="row">
        <%= button_tag :type => 'submit', :class => "waves-effect waves-light btn" do %>
         <%= t('crud.create') %> <i class="material-icons right">cloud</i>
        <% end %>
        <%= link_to(raw('<i class="material-icons right">delete_forever</i>'+ t('crud.delete') ),delete_admin_form_path(@form.id),class: 'btn waves-effect waves-light red') %>
      </div>
      
      
      
      
    <% end %>
  </div>
        
        
        
            
            
          
          
        </div>
      </div>
 </div>

</main>

app/views/admin/forms/edit_field.html.erb
<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">
        
        
        
        
        
 <div class="row">
    <% if @field.errors.full_messages.any? %>
      <% @field.errors.full_messages.each do |error_message| %>
        <% content_for :head do %>
          <%= toast(error_message,4000,['red']) %>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for @field ,url: update_field_admin_form_path,html: {class: 'col s12'},method: :POST do |f| %>
      <div class="row">

      <div class="input-field col s12">
        <%= f.select :field_type,%w[text_field text_area number_field check_box], {prompt: 'لطفا نوع فیلد را انتخاب کنید'}, {autofocus: 'true',class: 'browser-default'}  %>
        
        <br>
        <%= f.select :categories,Category.where(parent_id: nil).where(product_type_id: @field.product_type_id).first.subcategories.collect { |s| [s.name,s.id] }, {prompt: 'لطفا شاخه را انتخاب کنید'}, {:multiple => false,id: 'categories', autofocus: 'true', class: 'type_field browser-default',required: 'required'}  %>
        <br>
        <%= f.select :categories,Category.where(id: @field.categories).collect { |s| [s.name,s.id] }, {prompt: 'لطفا زیر شاخه را انتخاب کنید'}, {:multiple => false,id: 'subcategories', autofocus: 'true', class: 'type_field browser-default',required: 'required'}  %>
       </div>
       </div>
       
       
       <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name,class: 'validate', required: "required" %>
          <%= f.label :name, 'نام فیلد' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        <div class="input-field col s12">
          <%= f.text_field :permalink,class: 'validate', required: "required" %>
          <%= f.label :permalink, 'پرمالینک' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        
    
        
  
        
      
      
     </div>
       
      <div class="row">
      
        <%= button_tag :type => 'submit', :class => "waves-effect waves-light btn" do %>
         <i class="material-icons left">cloud</i>ثبت
        <% end %>
    

      </div>
      
      
      
      
    <% end %>
  </div>
        
        
        
            
            
          
          
        </div>
      </div>
 </div>

</main>

app/views/admin/forms/edit_prop.html.erb
<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">
        
        
        
        
        
 <div class="row">
    <% if @prop.errors.full_messages.any? %>
      <% @prop.errors.full_messages.each do |error_message| %>
        <% content_for :head do %>
          <%= toast(error_message,4000,['red']) %>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for @prop ,url: update_prop_admin_form_url,html: {class: 'col s12'},method: :POST do |f| %>
      <div class="row">

       
       
       <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name,class: 'validate', required: "required" %>
          <%= f.label :name, 'نام پروپرتی' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        <div class="input-field col s12">
          <%= f.text_field :permalink,class: 'validate', required: "required" %>
          <%= f.label :permalink, 'پرمالینک' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        
    
        
  
        
      
      
     </div>
       
      <div class="row">
      
        <%= button_tag :type => 'submit', :class => "waves-effect waves-light btn" do %>
         <i class="material-icons left">cloud</i>ثبت
        <% end %>
    

      </div>
      
      
      
      
    <% end %>
  </div>
        
        
        
            
            
          
          
        </div>
      </div>
 </div>

</main>

app/views/admin/forms/index.html.erb
<%# content_for :head do %>
  
  
<%# end %>

<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">

        <table class='striped highlight bordered'>
            <thead>
              <tr>
                  <th>ویرایش</th>
                 
                  <th>پرمالینک</th>
  <th>نام فرم</th>
              </tr>
            </thead>
    
            <tbody>
            <% @forms.each do |form| %>
              <tr>
                <td>
                  <%= link_to(raw('<i class="material-icons">delete_forever</i>'),delete_admin_form_path(form.id),class: 'small btn-floating waves-effect btn-small waves-light red', :data => {:confirm => t('alert.are_you_sure_delete')}) %>
                  <%= link_to(raw('<i class="material-icons">mode_edit</i>'),edit_admin_form_path(form.id),class: 'small btn-floating waves-effect btn-small waves-light blue') %>
                  <%= link_to(raw("<i class='material-icons'>#{form.lock? ? 'lock_outline':'lock_open'}</i>"),toggle_lock_admin_form_path(form.id),class: 'small btn-floating waves-effect btn-small waves-light green') %>
                  <%= link_to(raw("<i class='material-icons'>cast</i>"),show_fields_admin_form_path(form.id),class: 'small btn-floating waves-effect btn-small waves-light purple') %>
                </td>
                <td><%= form.permalink %></td>
                <td><%= form.name %></td>
              </tr>
            <% end %>
              
              
            
            </tbody>
          </table>
            
            
          
          
        </div>
      </div>
 </div>
<%= link_to(raw('<i class="material-icons">add</i>'),new_admin_form_path,class: 'btn-floating btn-large waves-effect waves-light red',style: 'position:fixed;bottom: 20px; left: 24px;') %>
</main>

app/views/admin/forms/new.html.erb
<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">
        
        
        
        
        
 <div class="row">
    <% if @form.errors.full_messages.any? %>
      <% @form.errors.full_messages.each do |error_message| %>
        <% content_for :head do %>
          <%= toast(error_message,4000,['red']) %>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for @form ,url: admin_forms_path,html: {class: 'col s12'},method: :POST do |f| %>
      <div class="row">

        <div class="input-field col s12">
          <%= f.text_field :name,class: 'validate', required: "required" %>
          <%= f.label :name, 'نام فرم' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        <div class="input-field col s12">
          <%= f.text_field :permalink,class: 'validate', required: "required" %>
          <%= f.label :permalink, 'پرمالینک' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
    
        
  
        
      
      
     </div>
       
      <div class="row">
      
        <%= button_tag :type => 'submit', :class => "waves-effect waves-light btn" do %>
         <i class="material-icons left">cloud</i>ثبت
        <% end %>
    

      </div>
      
      
      
      
    <% end %>
  </div>
        
        
        
            
            
          
          
        </div>
      </div>
 </div>

</main>

app/views/admin/forms/new_field.html.erb
<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">
        
        
        
        
        
 <div class="row">
    <% if @field.errors.full_messages.any? %>
      <% @field.errors.full_messages.each do |error_message| %>
        <% content_for :head do %>
          <%= toast(error_message,4000,['red']) %>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for @field ,url: save_fields_admin_form_path,html: {class: 'col s12'},method: :POST do |f| %>
      <div class="row">

      <div class="input-field col s12">
        <%= f.select :field_type,%w[text_field select_box text_area number_field check_box], {prompt: 'لطفا نوع فیلد را انتخاب کنید'}, {autofocus: 'true',class: 'browser-default',required: 'required'}  %>
        <br>

        <%= f.select :categories,Category.where(parent_id: nil).where(product_type_id: @field.product_type_id).first.subcategories.collect { |s| [s.name,s.id] }, {prompt: 'لطفا شاخه را انتخاب کنید'}, {:multiple => false,id: 'categories', autofocus: 'true', class: 'type_field browser-default',required: 'required'}  %>
        <br>
        <%= f.select :categories,[], {prompt: 'لطفا زیر شاخه را انتخاب کنید'}, {:multiple => false,id: 'subcategories', autofocus: 'true', class: 'type_field browser-default',required: 'required'}  %>
       </div>
       </div>
       
       
       <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name,class: 'validate', required: "required" %>
          <%= f.label :name, 'نام فیلد' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        <div class="input-field col s12">
          <%= f.text_field :permalink,class: 'validate', required: "required" %>
          <%= f.label :permalink, 'پرمالینک' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
      
     </div>
       
      <div class="row">
        <%= button_tag :type => 'submit', :class => "waves-effect waves-light btn" do %>
         <i class="material-icons left">cloud</i>ثبت
        <% end %>
      </div>
      
    <% end %>
  </div>
          
          
        </div>
      </div>
 </div>

</main>

app/views/admin/forms/new_prop.html.erb
<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">
        
        
        
        
        
 <div class="row">
    <% if @prop.errors.full_messages.any? %>
      <% @prop.errors.full_messages.each do |error_message| %>
        <% content_for :head do %>
          <%= toast(error_message,4000,['red']) %>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for @prop ,url: save_props_admin_form_path,html: {class: 'col s12'},method: :POST do |f| %>
       <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name,class: 'validate', required: "required" %>
          <%= f.label :name, 'نام پروپرتی' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        <div class="input-field col s12">
          <%= f.text_field :permalink,class: 'validate', required: "required" %>
          <%= f.label :permalink, 'پرمالینک' ,:'data-error' => "wrong", 'data-success'=> "" %>
        </div>
        
        
    
        
  
        
      
      
     </div>
       
      <div class="row">
      
        <%= button_tag :type => 'submit', :class => "waves-effect waves-light btn" do %>
         <i class="material-icons left">cloud</i>ثبت
        <% end %>
    

      </div>
      
      
      
      
    <% end %>
  </div>
        
        
        
            
            
          
          
        </div>
      </div>
 </div>

</main>

app/views/admin/forms/show.html.erb
<h1>Admin::Forms#show</h1>
<p>Find me in app/views/admin/forms/show.html.erb</p>

app/views/admin/forms/show_fields.html.erb
<%# content_for :head do %>
  
  
<%# end %>

<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">

        <table class='striped highlight bordered'>
            <thead>
              <tr>
                  <th>ویرایش</th>
                  
                 <th>
               
                    نوع فیلد
                  </th>
                 
                  <th>پرمالینک</th>
  <th>نام فیلد</th>
              </tr>
            </thead>
    
            <tbody>
            <% @fields.each do |field| %>
              <tr>
                <td>
                  <%= link_to(raw('<i class="material-icons">delete_forever</i>'),delete_field_admin_form_path(field.id),class: 'small btn-floating waves-effect btn-small waves-light red', :data => {:confirm => t('alert.are_you_sure_delete')}) %>
                  <%= link_to(raw('<i class="material-icons">mode_edit</i>'),edit_field_admin_form_path(field.id),class: 'small btn-floating waves-effect btn-small waves-light blue') %>
           <% if field.field_type=='select_box' %>  
                  <%= link_to(raw('<i class="material-icons">add</i>'),new_prop_admin_form_path(field.id),class: 'small btn-floating waves-effect btn-small waves-light green') %>
                  <%= link_to(raw('<i class="material-icons">cast</i>'),show_props_admin_form_path(field.id),class: 'small btn-floating waves-effect btn-small waves-light green') %>
              <% end %>

                </td>
               <td><%= field.field_type %></td>
                <td><%= field.permalink %></td>
                <td><%= field.name %></td>
              </tr>
            <% end %>
              
              
            
            </tbody>
          </table>
            
            
          
          
        </div>
      </div>
 </div>
<%= link_to(raw('<i class="material-icons">add</i>'),new_field_admin_form_path,class: 'btn-floating btn-large waves-effect waves-light red',style: 'position:fixed;bottom: 20px; left: 24px;') %>
</main>

app/views/admin/forms/show_props.html.erb
<%# content_for :head do %>
  
  
<%# end %>

<main>

 <div class="row">
      <div class="col s12 m12">
          
        <div class="card-panel white">

        <table class='striped highlight bordered'>
            <thead>
              <tr>
                  <th>ویرایش</th>
                  
                
                 
                  <th>پرمالینک</th>
  <th>نام پروپرتی</th>
              </tr>
            </thead>
    
            <tbody>
            <% @props.each do |prop| %>
              <tr>
                <td>
                  <%= link_to(raw('<i class="material-icons">delete_forever</i>'),delete_prop_admin_form_path(prop.id),class: 'small btn-floating waves-effect btn-small waves-light red', :data => {:confirm => t('alert.are_you_sure_delete')}) %>
                  <%= link_to(raw('<i class="material-icons">mode_edit</i>'),edit_prop_admin_form_path(prop.id),class: 'small btn-floating waves-effect btn-small waves-light blue') %>
        
                </td>
               
                <td><%= prop.permalink %></td>
                <td><%= prop.name %></td>
              </tr>
            <% end %>
              
              
            
            </tbody>
          </table>
            
            
          
          
        </div>
      </div>
 </div>
<%= link_to(raw('<i class="material-icons">add</i>'),new_prop_admin_form_path,class: 'btn-floating btn-large waves-effect waves-light red',style: 'position:fixed;bottom: 20px; left: 24px;') %>
</main>