config/routes.rb
Rails.application.routes.draw do

  

  match '', to: 'public/home#show_exposition', constraints: { subdomain: /^(?!www$)(.+)$/i },via: [:get]

  namespace :admin do
  get 'domain/index'
  end

  namespace :admin do
  get 'seller_chains/index'
  end

  namespace :admin do
  get 'seller_chains/new'
  end

  namespace :admin do
    resources :pages,controller: 'pages' do
       member do
        get 'delete'
        get 'toggle_lock'
       end
    end
    
    resources :categories,controller: 'categories' do
       member do
        get 'delete'
       end
    end
    
    
    resources :marketers,controller: 'marketer' do
       member do
        get 'delete'
       end
    end
    
    
     resources :sellers,controller: 'sellers' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'deliver_to_marketer'
       end
    end
    
     resources :comments,controller: 'comments' do
       member do
        get 'delete'
        get 'toggle_lock'
       end
    end
    
         resources :seller_chains,controller: 'seller_chains' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'requests'
       end
    end
    
    
     resources :forms,controller: 'forms' do
       member do
        get 'delete'
        get 'toggle_lock'
        get 'show_fields'
        get 'new_field'
        post 'save_fields'
        post 'update_field'
        get 'delete_field'
        get 'edit_field'
        
        get 'new_prop'
        post 'save_props'
        get 'delete_prop'
        get 'edit_prop'
        get 'show_props'
        post 'update_prop'
        
       end
    end
    
    
        resources :products,controller: 'products' do
       member do
        get 'delete'
        get 'block'
        get 'action_block'
        post 'action_block'
        get 'toggle_lock'
       end
    end
    
    
   resources :seller_products,controller: 'seller_products' do
       member do
        get 'delete'
        get 'vijeh'
        get 'toggle_lock'
       end
  end
    

    resources :seller_files,controller: 'seller_files' do
      member do
       get 'delete'
       get 'toggle_lock'
      end
   end

    
    get 'dashboard/setting'
    get 'dashboard/marketer_tasks'
        get 'dashboard/plans'
        get 'dashboard/packs'
        post 'dashboard/pay_plan'
        post 'dashboard/pay_plan_callback'
    post 'dashboard/update_setting'
    
    
  end

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations'}

post '/password/reset/sms' => 'public/home#reset_password', as: :reset_password

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end
  
  namespace :admin do
  get 'dashboard/index'
  get 'dashboard/change_development_mode'
  
  end

  namespace :admin do
  get 'dashboard/login'
  get 'dashboard/sms_service'
  get 'dashboard/setting'
  get 'dashboard/transaction'
  get 'dashboard/profile'
  post 'dashboard/update_profile'
   get 'dashboard/ads'
   get 'dashboard/password'
   post 'dashboard/update_password'
    post 'dashboard/send_ads'
  end

  namespace :admin do
  get 'dashboard/logout'
  end
  get 'update',to: 'public/home#update',:as => :update

  get 'callBackUpgrade',to: 'public/home#callBackUpgrade'
  post 'callBackUpgrade',to: 'public/home#callBackUpgrade'

  get 'product/favorite',to: 'public/home#favorite'
  get 'new_product',to: 'public/home#new_product',:as => :new_product
  get 'new_product/:id',to: 'public/home#new_product'
  post 'create_product/:id',to: 'public/home#create_product',:as => :create_product
  post 'update_product/:id',to: 'public/home#update_product',:as => :update_product

  post 'getFields/:id',to: 'public/home#getFields',:as => :get_fields

  
  get 'upgrade_product/:id/:pos',to: 'public/home#upgrade_product'
  get 'product/:id',to: 'public/home#product',:as => :product_show
  get 'products',to: 'public/home#products',:as => :products_show
  get 'destroy_product',to: 'public/home#destroy_product',:as => :destroy_product
  get 'file/:id',to: 'public/home#file',:as => :file_show
  get 'exposition/show/:id',to: 'public/exposition#show',:as => :exposition_show
  post 'exposition/create_comment',to: 'public/exposition#create_comment',:as => :create_comments
  get 'expositions',to: 'public/exposition#expositions',:as => :expositions_show

  get 'exposition/follow',to: 'public/exposition#follow'
  get 'exposition/rate',to: 'public/exposition#rate'
  get 'page/:permalink' => 'public/home#page',as: :page
  
 namespace :public do
  namespace :home do
    get 'register_exposition'
    post 'save_exposition'
    get 'inbox'
    get 'following'
    get 'following_post'
    get 'category'
    get 'favorites'
    get 'search'
   
    
  end
  
    resources :tickets,controller: 'tickets' do
     member do
        get 'conversation'
        post 'save_conversation'
        
       end
    end
 
  
  
end

  root 'public/home#index'

  namespace :api do
    namespace :v1 do
      
    get 'categories' 
    get 'getEditProduct/:id', action: :getEditProduct
    get 'forgot_password/:phone', action: :forgot_password
    
    get 'subcategories/:id' , action: :subcategories
    get 'expositions/:type',action: :expositions
    get 'exposition/:id',action: :exposition
    get 'tickets/:token',action: :tickets
    get 'conversation/:token',action: :conversation
    get 'profile/:token',action: :profile
    get 'update_password/:token',action: :update_password
    get 'update_profile/:token',action: :update_profile
    post 'updateProduct/:id',action: :updateProduct
    get 'product_categories/:token',action: :product_categories
    get 'slider',action: :slider
    get 'category_fields/:token',action: :category_fields
    get 'save_product/:token',action: :save_product
    get 'verify/:token',action: :verify
    get 'check_username/:identity',action: :check_username
    
    get 'register_exposition',action: :register_exposition
    
    post 'save_product/:token',action: :save_product
    post 'register_exposition_c',action: :register_exposition_c
    
    
    get 'delete_product/:token',action: :delete_product
    get 'search/:type',action: :search
    get 'exposition_comments/:id',action: :exposition_comments
    
    
    get 'favorite/:token',action: :favorite
    get 'marketer_sellers/:token',action: :marketer_sellers
    get 'add_seller/:token',action: :add_seller
    
    get 'follow/:id',action: :follow
    get 'following/:token',action: :following
    get 'exposition_filters/:id',action: :exposition_filters
    get 'filter/:id',action: :filter
    get 'build_conversation/:token',action: :build_conversation
    get 'checkNewMessage/:token',action: :checkNewMessage
    get 'startmessage/:token',action: :startmessage
    get 'hasNewTickets/:token',action: :hasNewTickets
    
    
    post 'save_product_image/:id',action: :save_product_image
    get 'nearby',action: :nearby
    get 'show_exposition/:id',action: :show_exposition
    get 'products/:type',action: :products
    get 'product/:id',action: :product
    get 'save_comment/:id',action: :save_comment
    
    get 'favorites/:token',action: :favorites
    get 'product_comments/:id',action: :product_comments
    match 'login',via: [:get,:post,:options]
    match 'register',via: [:get,:post,:options]
      

    end
    
    
  end
  
  
  
  
end

app/views/partials/admin/_aside_add_seller.html.erb
<header>
<nav class="top-nav">
        <div class="container">
          <div class="nav-wrapper">
              <ul class="align left">
                  <li>
                      <a class="page-title" id='help'>راهنما</a>
                  </li>
              </ul>
            <ul class="align right">
                  <li>
                      <a class="user_name">
                          بازاریاب 
                          <%= current_user.name %>
                      </a>
                  </li>
              </ul>
          </div>
        </div>
      </nav>
    
    <ul id="nav-mobile" class="side-nav fixed text-right" style="background-color:#2c3e50 !important;">
        
        <li class="logo align center">
     
        </li>

        <li style="text-align:center !important;">
           <%= image_tag 'https://secure.gravatar.com/avatar/ddd?s=180' %>
        </li>
        
     <li class="bold">
          <span class="new badge green left"><%= current_user.marketer_tasks.size %></span>
         <%= link_to 'لیست کارها',admin_dashboard_marketer_tasks_path,class: 'waves-effect waves-teal' %>
        </li>
    
        <li class="bold">
         <%= link_to 'فروشگاه ها',admin_sellers_path,class: 'waves-effect waves-teal' %>
        </li>
           <% if Product.where(accept: false).length >= 1 %>
         <li class="bold">
                     <span class="new badge green left"><%= Product.where(accept: false).length %></span>
        <%= link_to 'محصولات تایید نشده',admin_products_path(unaccept: true),class: 'waves-effect waves-teal' %>

        </li>
        <% end %>
        

     <% if Product.where(accept: false).where(fori: true).length >= 1 %>
         <li class="bold">
                     <span class="new badge green left"><%= Product.where(accept: false).where(fori: true).length %></span>
        <%= link_to 'آگهی های ویژه تایید نشده',admin_products_path(unaccept: true,vijeh: true),class: 'waves-effect waves-teal' %>

        </li>
        <% end %>
            
           <li class="bold">
            <%= link_to 'رمزعبور',admin_dashboard_password_path,class: 'waves-effect waves-teal' %>
             
</li>
        <li class="bold">

          <%= link_to 'خروج' ,destroy_user_session_path,class: "waves-effect waves-teal", :method => :delete %>
          </li>
            
       
      </ul>
   </header>

app/views/partials/admin/_aside_admin.html.erb
<header>
<nav class="top-nav">
        <div class="container">
          <div class="nav-wrapper">
              
              <ul class="align left">
                  <li>
                      <%= link_to 'خروج' ,destroy_user_session_path,class: "page-title", :method => :delete %>
                  </li>
              </ul>
              
               <div class="switch align left white-text">
    <label class='white-text'>
      
      <input type="checkbox" id='development'>
      <span class="lever"></span>
      توسعه
    </label>
  </div>

              
            <ul class="align right">
                  <li>
                      <a class="user_name">
                           
                          <%= current_user.name %> خوش امدید
                      </a>
                  </li>
              </ul>
          
          </div>
        </div>
      </nav>
    
    <ul id="nav-mobile" class="side-nav fixed text-right" style="background-color:#2c3e50 !important;">
        
        <li class="logo align center">
            <a id="logo-container"  style="text-align:center !important;" href="http://materializecss.com/" class="brand-logo">
            
            </a>
        </li>

        <li style="text-align:center !important;">
           <%= gravatar_for current_user %>
        </li>
    
        <li class="bold"><a href="/admin/dashboard/index" class="waves-effect waves-teal">
            پیشخوان
            </a></li>
            
        <li class="bold">
        <%= link_to 'محصولات',admin_products_path,class: 'waves-effect waves-teal' %>
        </li>
        
        <% if Product.where(accept: false).length >= 1 %>
         <li class="bold">
                     <span class="new badge green left"><%= Product.where(accept: false).length %></span>
        <%= link_to 'محصولات تایید نشده',admin_products_path(unaccept: true),class: 'waves-effect waves-teal' %>

        </li>
        <% end %>
        

     <% if Product.where(accept: false).where(fori: true).length >= 1 %>
         <li class="bold">
                     <span class="new badge green left"><%= Product.where(accept: false).where(fori: true).length %></span>
        <%= link_to 'آگهی های ویژه تایید نشده',admin_products_path(unaccept: true,vijeh: true),class: 'waves-effect waves-teal' %>

        </li>
        <% end %>


           <li class="bold">
                 <%= link_to 'دسته بندی ها',admin_categories_path,class: 'waves-effect waves-teal' %>
               </li>
               
                      <li class="bold">
         <%= link_to 'فرم ها',admin_forms_path,class: 'waves-effect waves-teal' %>

      </li>
 
        <li class="bold">
         <%= link_to 'فروشگاه ها',admin_sellers_path,class: 'waves-effect waves-teal' %>
        </li>
        
        <% if User.sellers.where(exposition_accept: false).length >= 1 %>
            <li class="bold">
                <span class="new badge green left"><%= User.sellers.where(exposition_accept: false).length %></span>
             <%= link_to 'فروشگاه های تایید نشده',admin_sellers_path(unaccept: true),class: 'waves-effect waves-teal' %>
            </li>
        <% end %>
        
            
        <li class="bold">
            <%= link_to 'بازاریاب ها',admin_marketers_path,class: 'waves-effect waves-teal' %>
        </li>
        
        <li class="bold">
         <%= link_to 'تراکنش ها',admin_dashboard_transaction_path,class: 'waves-effect waves-teal' %>

      </li>
      
      
          <li class="bold">
               <%= link_to 'پیام کوتاه',admin_dashboard_sms_service_path,class: 'waves-effect waves-teal' %>
            </li>
        <li class="bold">
            <%= link_to 'صفحات',admin_pages_path,class: 'waves-effect waves-teal' %>
        </li>
            
            

            
               
                      
        <li class="bold">
            <%= link_to 'نظرات',admin_comments_path,class: 'waves-effect waves-teal' %>
        </li>
        

    <li class="bold">
                 <%= link_to 'تنظیمات',admin_dashboard_setting_path,class: 'waves-effect waves-teal' %>
    </li>
    
      
      <li class="bold">
          
          <%= link_to 'خروج' ,destroy_user_session_path,class: "waves-effect waves-teal", :method => :delete %>
     
        
        </li>
        
        
      </ul>





   </header>

app/views/partials/admin/_aside_seller.html.erb
<header>
<nav class="top-nav">
        <div class="container">
          <div class="nav-wrapper">
              
              <ul class="align left">
                  <li>
                      <a class="page-title" id='help'>راهنما</a>
                  </li>
                        <li>
                  <%= link_to 'خروج' ,destroy_user_session_path,class: "page-title", :method => :delete %>
                  </li>
              </ul>
              
 
  </div>

              
            <ul class="align right">
                  <li>
                      <a class="user_name">
                           
                       <%= current_user.name %>   خوش امدید 
                      </a>
                  </li>
              </ul>
          
          </div>
        </div>
      </nav>
    
    <ul id="nav-mobile" class="side-nav fixed text-right" style="background-color:#2c3e50 !important;">
        
        <li class="logo align center">
            <a id="logo-container"  style="text-align:center !important;" href="<%= exposition_show_url(current_user.id) %>" target='_blank' class="brand-logo">
            فروشگاه <%= current_user.exposition_name %>
            </a>
        </li>

        <li style="text-align:center !important;">
            <%= image_tag 'https://secure.gravatar.com/avatar/ddd?s=180' %>
        </li>
    
        <li class="bold"><a href="/admin/dashboard/index" class="waves-effect waves-teal">
            پیشخوان
            </a></li>
            
        <% if current_user.exposition_accept? %>
        
        <li class="bold">
            <%= link_to 'محصولات',admin_seller_products_path,class: 'waves-effect waves-teal' %>
             

        </li>
        

        <li class="bold">
            <%= link_to 'فروش فایل',admin_seller_files_path,class: 'waves-effect waves-teal' %>
             

        </li>



           <li class="bold">
            <%= link_to 'ارسال گروهی',admin_dashboard_ads_path,class: 'waves-effect waves-teal' %>
             

        </li>
        
              
        <li class="bold">
            <%= link_to 'شعبات',admin_seller_chains_path,class: 'waves-effect waves-teal' %>
             

        </li>
        
                      
        <li class="bold">
            <%= link_to 'درخواست ها',requests_admin_seller_chain_path(current_user),class: 'waves-effect waves-teal' %>
             

        </li>
        
        
        
        
               </li>
        
           <li class="bold">
            <%= link_to 'رمزعبور',admin_dashboard_password_path,class: 'waves-effect waves-teal' %>
             

        </li>
        
        
        <li class="bold">
            <span class="new badge green left"><%= Comment.where(accept: false).where(product_id: current_user.products.ids).length %></span>
            <%= link_to 'نظرات',admin_comments_path,class: 'waves-effect waves-teal' %>
        </li>
        
      
        <li class="bold">
            <span class="new badge green left">
                <%= Ticketmessage.where(ticket_id: Ticket.where('user_id = ? OR user_two = ?',current_user.id,current_user.id).ids).where(seen: false).length %></span>
       <%= link_to 'پیام ها',public_tickets_path,class: 'waves-effect waves-teal' %>
  </li>
  
  <% end %>
  
  
        
        <li class="bold">
            <a href="/admin/dashboard/profile" class="waves-effect waves-teal">
پروفایل
        </a>
        </li>
        
          
              <li class="bold">
            <a href="/admin/dashboard/plans" class="waves-effect waves-teal">
پلن ها
        </a>
        </li> 
             
                    <li class="bold">
            <a href="/admin/dashboard/packs" class="waves-effect waves-teal">
پک ها
        </a>
        </li> 

           
      </ul>





   </header>